version: "3.3"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - wp_content:/var/www/html/wp_content
    depends_on:
      - wordpress
    restart: always
    networks:
      - wordpress_network
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
    networks:
      - wordpress_network
    expose:
      - 3306
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    env_file: .env
    volumes:
      - wp_content:/var/www/html/wp_content
    networks:
      - wordpress_network
    expose:
      - 9000
volumes:
  wp_content:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: /home/adinari/tmp/wp_content
  db_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: /home/adinari/tmp/db_data
networks:
  wordpress_network:
    driver: bridge
